services:
  app:
    container_name: "sbcontainer"
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/demodb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123
    depends_on:
      - postgres_db
    networks:
      - socolaNetwork

  postgres_db:
    container_name: "postgres_db"
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "demodb"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - socolaNetwork


networks:
  socolaNetwork:
    driver: bridge

volumes:
  postgres-data: